version: "3.8"

services:
  postgres:
    image: postgres:latest
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres
      POSTGRES_HOST: "localhost"
    ports:
      - "5433:5432"
    networks:
      - solana-indexing

  app:
    build: .
    container_name: solana-sink
    restart: always
    depends_on:
      - postgres
    environment:
      TOKEN: "eyJhbGciOiJLTVNFUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjIwMjQ4MTk3NDAsImp0aSI6ImY3YWU0OTM1LTkyNjMtNDI2NC1iZjFkLTM1YTA2NDVmOWYxOCIsImlhdCI6MTcwOTQ1OTc0MCwiaXNzIjoiZGZ1c2UuaW8iLCJzdWIiOiIwbHVmeWJjZmQzYWZhZGJiZTUxNDciLCJ2IjoxLCJha2kiOiI1Zjg0YzIwOGVjYjhiMjhjNTgwNGE2YjdmMDE1ZjcxNDk3ODdiYjc1NTE2YzViNDMzNmNjODJmYzdhYmQyZTAwIiwidWlkIjoiMGx1ZnliY2ZkM2FmYWRiYmU1MTQ3In0.yHyfs_lXl2yvAhWktQcuI1gfXtpohRa_kH0-8liYqiyC8jehnG1qP3PaKV5eFS4OXu_FZJq0zERWMTe0AXEjyA"
      START_BLOCK: 245473147
    ports:
      - "3000:3000"
    networks:
      - solana-indexing

networks:
  solana-indexing:
    name: solana-indexing
